# Generated by Django 5.2.8 on 2025-12-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraftid', models.IntegerField(db_column='AircraftID', primary_key=True, serialize=False)),
                ('manufactureyear', models.IntegerField(db_column='ManufactureYear')),
                ('lastmaintenancedate', models.DateField(db_column='LastMaintenanceDate')),
            ],
            options={
                'db_table': 'AIRCRAFT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('aircrafttypecode', models.IntegerField(db_column='AircraftTypeCode', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_column='TypeName', max_length=100)),
                ('maxpassengers', models.IntegerField(db_column='MaxPassengers')),
                ('maintenancetypeid', models.IntegerField(db_column='MaintenanceTypeID')),
            ],
            options={
                'db_table': 'AIRCRAFT_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airlineid', models.IntegerField(db_column='AirlineID', primary_key=True, serialize=False)),
                ('airlinename', models.CharField(db_column='AirlineName', max_length=100)),
                ('airlineicao', models.CharField(db_column='AirlineICAO', max_length=10)),
                ('foundedyear', models.IntegerField(db_column='FoundedYear')),
            ],
            options={
                'db_table': 'AIRLINE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airportcode', models.IntegerField(db_column='AirportCode', primary_key=True, serialize=False)),
                ('airportname', models.CharField(db_column='AirportName', max_length=150)),
                ('latitude', models.DecimalField(db_column='Latitude', decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(db_column='Longitude', decimal_places=6, max_digits=10)),
                ('timezone', models.CharField(db_column='Timezone', max_length=50)),
            ],
            options={
                'db_table': 'AIRPORT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('allianceid', models.IntegerField(db_column='AllianceID', primary_key=True, serialize=False)),
                ('alliancename', models.CharField(db_column='AllianceName', max_length=100)),
            ],
            options={
                'db_table': 'ALLIANCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingid', models.IntegerField(db_column='BookingID', primary_key=True, serialize=False)),
                ('bookingdate', models.DateTimeField(db_column='BookingDate')),
                ('totalamount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=10)),
                ('bookingstatus', models.CharField(db_column='BookingStatus', max_length=20)),
                ('bookingchannel', models.CharField(db_column='BookingChannel', max_length=20)),
            ],
            options={
                'db_table': 'BOOKING',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityid', models.IntegerField(db_column='CityID', primary_key=True, serialize=False)),
                ('cityname', models.CharField(db_column='CityName', max_length=100)),
            ],
            options={
                'db_table': 'CITY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countrycode', models.IntegerField(db_column='CountryCode', primary_key=True, serialize=False)),
                ('countryname', models.CharField(db_column='CountryName', max_length=100)),
            ],
            options={
                'db_table': 'COUNTRY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currencycode', models.IntegerField(db_column='CurrencyCode', primary_key=True, serialize=False)),
                ('currencyname', models.CharField(db_column='CurrencyName', max_length=50)),
                ('currencysymbol', models.CharField(db_column='CurrencySymbol', max_length=3)),
            ],
            options={
                'db_table': 'CURRENCY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightid', models.IntegerField(db_column='FlightID', primary_key=True, serialize=False)),
                ('flightnumber', models.CharField(db_column='FlightNumber', max_length=20)),
                ('scheduleddeparture', models.DateTimeField(db_column='ScheduledDeparture')),
                ('scheduledarrival', models.DateTimeField(db_column='ScheduledArrival')),
                ('actualdeparture', models.DateTimeField(blank=True, db_column='ActualDeparture', null=True)),
                ('actualarrival', models.DateTimeField(blank=True, db_column='ActualArrival', null=True)),
                ('flightstatus', models.CharField(db_column='FlightStatus', max_length=20)),
                ('departuregatenumber', models.IntegerField(db_column='DepartureGateNumber')),
                ('arrivalgatenumber', models.IntegerField(db_column='ArrivalGateNumber')),
            ],
            options={
                'db_table': 'FLIGHT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('gatenumber', models.IntegerField(db_column='GateNumber', primary_key=True, serialize=False)),
                ('gatetype', models.IntegerField(db_column='GateType')),
                ('isactive', models.BooleanField(db_column='IsActive')),
            ],
            options={
                'db_table': 'GATE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passengerid', models.IntegerField(db_column='PassengerID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('phone', models.CharField(db_column='Phone', max_length=20)),
                ('dateofbirth', models.DateField(db_column='DateOfBirth')),
                ('passportnumber', models.CharField(db_column='PassportNumber', max_length=50, unique=True)),
                ('nationality', models.CharField(db_column='Nationality', max_length=50)),
            ],
            options={
                'db_table': 'PASSENGER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('seatclass', models.IntegerField(db_column='SeatClass', primary_key=True, serialize=False)),
                ('basefare', models.IntegerField(db_column='BaseFare')),
                ('baggageallowance', models.IntegerField(db_column='BaggageAllowance')),
            ],
            options={
                'db_table': 'SEAT_CLASS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('terminalid', models.IntegerField(db_column='TerminalID', primary_key=True, serialize=False)),
                ('terminalname', models.CharField(db_column='TerminalName', max_length=50)),
                ('isinternational', models.BooleanField(db_column='IsInternational')),
            ],
            options={
                'db_table': 'TERMINAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketid', models.IntegerField(db_column='TicketID', primary_key=True, serialize=False)),
                ('seatnumber', models.CharField(db_column='SeatNumber', max_length=10)),
                ('ticketstatus', models.CharField(db_column='TicketStatus', max_length=20)),
                ('checkedina', models.DateTimeField(blank=True, db_column='CheckedInAt', null=True)),
            ],
            options={
                'db_table': 'TICKET',
                'managed': False,
            },
        ),
    ]
