# Generated by Django 5.2.8 on 2025-12-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('crewid', models.IntegerField(db_column='CrewID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('dateofbirth', models.DateField(db_column='DateOfBirth')),
                ('hiredate', models.DateField(db_column='HireDate')),
                ('crewtype', models.IntegerField(db_column='CrewType')),
            ],
            options={
                'db_table': 'CREW_MEMBER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('maintenanceid', models.IntegerField(db_column='MaintenanceID', primary_key=True, serialize=False)),
                ('maintenancedate', models.DateField(db_column='MaintenanceDate')),
                ('description', models.TextField(db_column='Description')),
                ('cost', models.DecimalField(db_column='Cost', decimal_places=2, max_digits=10)),
                ('nextduedate', models.DateField(db_column='NextDueDate')),
            ],
            options={
                'db_table': 'MAINTENANCE_RECORD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('maintenancetypeid', models.IntegerField(db_column='MaintenanceTypeID', primary_key=True, serialize=False)),
                ('maintenancetype', models.CharField(db_column='MaintenanceType', max_length=100)),
            ],
            options={
                'db_table': 'MAINTENANCE_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('routeid', models.IntegerField(db_column='RouteID', primary_key=True, serialize=False)),
                ('distancekm', models.IntegerField(db_column='DistanceKM')),
                ('estimateddurationmins', models.IntegerField(db_column='EstimatedDurationMins')),
                ('routetype', models.IntegerField(db_column='RouteType')),
            ],
            options={
                'db_table': 'ROUTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('technicianid', models.IntegerField(db_column='TechnicianID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('specialization', models.CharField(db_column='Specialization', max_length=100)),
            ],
            options={
                'db_table': 'TECHNICIAN',
                'managed': False,
            },
        ),
    ]
